---
- name: Enable GPIO pins
  blockinfile:
    dest: /boot/config.txt
    block: |  
      # 1wire GPIO
      dtoverlay=w1-gpio
      gpiopin=4

- name: Install "node-red-contrib-1wire".
  npm:
    name: node-red-contrib-1wire
    global: yes
  tags: new