---
- name: 'Install "nodered" and related packages'
  apt: name={{item}} state=installed
  with_items:
    - nodered
    - npm

- name: Start Node-Red on boot    
  service: 
    name=nodered
    state=started
    enabled=yes