---
- name: Add Pagekite source
  apt_repository:
    repo: deb http://pagekite.net/pk/deb/ pagekite main
    state: present

- name: Add PageKite packaging key
  apt_key:
    keyserver: keys.gnupg.net
    id: AED248B1C7B2CAC3

- name: Install Pagekite
  apt: 
    name: pagekite 
    state: installed
    allow_unauthenticated: yes
    
- name: Configure Pagekite account
  copy: src=./pagekite_10_account.rc dest=/etc/pagekite.d/10_account.rc mode=0600

- name: Configure Pagekite
  command: mv /etc/pagekite.d/80_sshd.rc.sample /etc/pagekite.d/80_sshd.rc
  
- name: Restart Pagekite
  service:
    name: pagekite
    state: restarted
  tags: new
  