---
#- include: hostname.yml

- name: Setup ssh key
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', '/Users/crowe/.ssh/id_rsa.pub') }}"
  register: add_identity_key
    
- name: Disable password login
  lineinfile: dest="/etc/ssh/sshd_config" regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
  when: add_identity_key|success and not add_identity_key|skipped
  
- name: restart sshd
  service: name=ssh state=restarted